### PR TITLE
fix(pam): build zbus with the feature set that actually compiles standalone

### PR DESCRIPTION
**Pull request by tyvsmith**
## What

Fixes the merge-blocker from REV-107's principal-architect review: `cargo build -p pam-facelock` did not compile on its own.

## Reproduction

```
$ cargo build -p pam-facelock
error: Either "async-io" (default) or "tokio" must be enabled
error[E0433]: cannot find module or crate `async_lock` ...
error[E0433]: cannot find module or crate `async_process` ...
error: could not compile `zbus` (lib) due to 21 previous errors
```

`crates/pam-facelock/Cargo.toml` declared:

```toml
zbus = { version = "5", default-features = false, features = ["blocking"] }
```

In zbus 5 the `zbus::blocking` module the PAM code uses (`zbus::blocking::Connection`, `::Proxy`, `::fdo::DBusProxy`, `::connection::Builder`) is gated by **`blocking-api`**, not `blocking`. `blocking` is only a sub-item of the async-io bundle that turns on an unrelated thread-pool crate. With `default-features = false` and no runtime selected, the feature set is incoherent and zbus cannot compile.

## Why it hid

`cargo build --workspace` unifies features across crates. `facelock-cli` and `facelock-polkit` both request `zbus = { ..., features = ["tokio", "blocking-api"] }` for the same zbus, so the workspace build silently repaired pam-facelock's set. `cargo tree` also resolved fine (58 crates) — graph resolution succeeds; it is not a compile check. Only a standalone `cargo build -p pam-facelock` exposed it.

This means the memory note claiming "pam solo-test breakage is pre-existing" was **wrong**. `main` declares `zbus = { version = "5", features = ["blocking"] }` (defaults *on*), which builds standalone via the async-io backend. This PR's commit `54a2935 fix(pam): build zbus without default features (C1)` added `default-features = false` and is what introduced the breakage.

## The fix

```toml
zbus = { version = "5", default-features = false, features = ["tokio", "blocking-api"] }
```

Matches `facelock-cli` and `facelock-polkit` exactly. pam-facelock now builds and tests in isolation (29 tests pass). The async-io thread-pool crates (`async-channel`, `async-task`, `blocking`, `piper`) drop out of `Cargo.lock`.

## Guard re-tuning (measured)

The CI guard forbade `async-io|async-signal|signal-hook-registry|polling`. The correct tokio backend pulls **`signal-hook-registry`** transitively via tokio's `process` feature, so the old guard would have rejected this very fix (it was calibrated against the broken tree).

Measured post-fix dependency set (`cargo tree -p pam-facelock --edges normal --prefix none`):
- **Added** by tokio backend: `bytes`, `errno`, `mio`, `signal-hook-registry`, `socket2`, `tokio`
- **Removed** async-io backend: `async-channel`, `async-task`, `atomic-waker`, `blocking`, `concurrent-queue`, `crossbeam-utils`, `piper`

New guard forbids the async-io runtime backend directly — `async-io`, `async-signal`, `polling`, plus `async-executor`, `async-fs`, `async-lock` — and drops `signal-hook-registry`. Verified: the new regex matches nothing in the fixed tree and still catches 5 markers in `main`'s async-io tree.

## Isolation build in CI

Added a `Build pam-facelock in isolation` step (`cargo build -p pam-facelock`, not `--workspace`) next to the guard, so this class of bug can no longer hide behind feature unification. Mirrored locally as `just check-pam-standalone`, wired into `just check`.

## Crate-count story (C1 goal holds)

| Tree | Crates | Compiles standalone? |
|------|--------|----------------------|
| pre-#107 baseline (`main`, async-io backend) | 68 | yes |
| #107 as-shipped (`default-features=false, ["blocking"]`) | 58 (resolves) | **no** |
| this fix (`["tokio","blocking-api"]`) | **57** | yes |

The fix is one crate smaller than the number #107 claimed (58) and 11 smaller than the 68-crate baseline — C1's dependency-shrink goal is preserved and slightly improved.

## Review finding

Fixes REV-107's merge-blocker: pam-facelock failing to build standalone.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by tyvsmith** [comment]
Superseded by #136, which merged the exact gate-verified integration/post-review tree into main.
